### ISSUE TITLE
How to read/interpret the flame graph?

### ISSUE THREAD

**Issue by stevenharman** [djudd/reap#8]
Any tips on how to interpret the heap dump flame graphs? I am guessing root objects at the top, with each layer down being a traversal down the dominance tree? Is the width the amount of memory referenced? Number of objects further down the tree?

Pointers and tips would be greatly appreciated. Thank you!

**Comment by djudd** [comment]
Your guesses are correct! It might help to explore some of the text output for an alternate view if something is confusing but it sounds like you've got the basics.

**Comment by stevenharman** [comment]
Great, just wanted to be sure I was interpreting what I was seeing correctly. Sometimes what you see doesn't fully make sense if you don't keep the limit to `-c` you passed in. Thanks!

**Comment by stevenharman** [comment]
I ended up [writing up my recent memory leak adventure](https://stevenharman.net/so-we-have-a-memory-leak#analyze-the-heap-dumps), and talked about `reap`, how to read the graphs`, etc… thanks again for the tool!
